### PR TITLE
feat: Fix conversion of buffer to Boolean

### PR DESCRIPTION
**Pull request by Dynee**
Calling the Boolean constructor on a Buffer object in `process-columnar-results.js` always returns true regardless if the value is true or not.  This is noticeable when
Creating a query using the ST_CONTAINS function as a column in a select statement.
For example,

`SELECT id, name ST_CONTAINS(omnisci_geo, ST_GeomFromText(‘POINT(-87.3592959471789 35.0011799880309)’, 4326) from omnisci_states`

Should return true for only Tennessee however, it returns true for each state
(hopefully I submitted this right lol)

Jira Issue
[FE-14440]

# Merge Checklist
## :wrench: Issue(s) fixed:
- [ ] Author referenced issue(s) fixed by this PR:
- [ ] Fixes #0

## :smoking: Smoke Test
- [ ] Works in chrome
- [ ] Works in firefox
- [ ] Works in safari
- [ ] Works in ie edge
- [ ] Works in ie 11

## :ship: Merge
- [ ] author crafted PR's title into release-worthy commit message.

[FE-14440]: https://omnisci.atlassian.net/browse/FE-14440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by israelvicars** [comment]
retest this please

**Review by bmatcuk — CHANGES_REQUESTED** [review]
Javascript only supports numbers up to 53? bits of precision? I forget the exact size. For any columns that are larger (say, 64-bits of precision), thrift automatically uses some kind of internal "BigInt" class to represent them, even if the value itself fits inside 53-bits.

My guess is that this particular use case is returning a 64-bit result, so thrift is using the BigInt implementation. But, there's the possibility that this won't always be the case: ie, the SQL query may return a bool result, represented as a smaller integer, so thrift won't use BigInt and there'll be no buffer.

I believe a safer solution would be something like:

```javascript
function valueToBoolean(value) {
  // BigInts have a toNumber method
  if (value.toNumber) {
    return Boolean(value.toNumber(true))
  }
  return Boolean(value)
}
```

Additionally, the two BOOL cases in `process-row-results.js` may also need updated to use this utility function.

Note: I'm pretty sure the jenkins build always fails 🤷

**Comment by Dynee** [comment]
Thank you for the insight! That definitely makes sense, I didn't know about thrift automatically using a BigInt to represent the value.  I updated with the requested changes.  I also wasn't sure about the jenkins build failing, as far as I could tell all the tests passed locally. 😄

**Comment by zNeill** [comment]
I suspect that the mapd-connector-pr job is failing due to the source change being in a forked repository, it seems to be unable to find the commit in Jenkins.

```
> git rev-parse 55fd0f9d3f6fe5d33e79c6f995c55a387cd0e491^{commit} # timeout=10
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
Finished: FAILURE
```

**Comment by bmatcuk** [comment]
Cool, thanks @Dynee - have you had a chance to test these changes with real data to make sure it works? I'm only guessing at the BigInt thing based on my past experience working with the thrift stuff.

**Comment by Dynee** [comment]
no problem, @bmatcuk I tested using the `omnisci_states` and `omnisci_countries` tables provided by default,
I tested the query above and a select case query like `select level, case when level = 1 then true else false end from omnisci_countries` both returned the expected values.

so far I haven't been able to find a query where it returns unexpected results.

**Review by bmatcuk — APPROVED** [review]
Cool, in that case, it looks good to me! :shipit:

**Pull request merged**
