### PR TITLE
Codecov should not be a dependency

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by domoritz** [comment]
Can you merge this @jrajav?

**Comment by domoritz** [comment]
It would be great to merge this since I otherwise get tons of warnings in my builds.

**Comment by jrajav** [comment]
@domoritz This looks like a fine change - thank you for the contribution!

Please make sure you merge master again prior to merge since we updated the Travis build just now. If it passes again, you're good to go for merge!

**Comment by domoritz** [comment]
Done.

**Comment by domoritz** [comment]
@jrajav Can you merge and release this? I keep getting security warnings because of this.

**Comment by jrajav** [comment]
@domoritz Done! We'll release sometime within the next few weeks.

**Comment by domoritz** [comment]
Sweet, thanks.

**Pull request merged**
